# Use the official Python image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy requirements file and install dependencies
COPY frontend/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the files into the container
COPY frontend/front.py /app/
COPY frontend/templates/displaymessages.html /app/templates/
COPY frontend/templates/sendmessage.html /app/templates/


# Run the Flask app
CMD ["python", "front.py"]
