version: "v2.32.1"
networks:
  dev:
  
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./certs:/etc/nginx/certs
    ports:
    - "80:80"
    - "443:443"
    depends_on:
      - front
      - back
    networks:
    - dev
  
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6969
      POSTGRES_DB: postgres
    ports: 
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    networks:
    - dev


  back:
    build:
      context: .
      dockerfile: Dockerfile_back
    container_name: backend 
    depends_on:
      - db
    volumes:
      - /backend/.gitignore/db_config.ini:/app/dbconfig.ini
    ports:
      - "5002:5002"
    networks:
    - dev


  front:
    build:
      context: .
      dockerfile: Dockerfile_front
    container_name: frontend
    depends_on:
      - back
    volumes:
      - ./frontend/templates:/app/templates
    ports:
      - "5000:5000"
    networks:
    - dev

volumes:
  db_data: