# Dockerfile.back
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy necessary files
COPY dbcrud.py /app/
COPY .gitignore/db_config.ini /app/.gitignore/

# Command to run the app
CMD ["python", "dbcrud.py"]
